config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get '/ratings', to: 'ratings#index'
  get '/stats', to: 'static_pages#stats'

  post '/ratings', to: 'ratings#create', as: 'add_rating'
  post 'new_movie', to: 'ratings#new_movie', as: 'new_movie'
  post 'select_movie', to: 'ratings#select_movie', as: 'select_movie'

  # Defines the root path route ("/")
  root 'ratings#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  has_many :ratings

  validates :title, presence: true, length: { minimum: 1, maximum: 600 } # about 3x the length of the longest title ever made
end

app/models/rating.rb
# frozen_string_literal: true

class Rating < ApplicationRecord
  belongs_to :movie
  accepts_nested_attributes_for :movie
  belongs_to :user

  scope :grouped_and_sorted_by_date, -> { all.group_by(&:watched_date).sort_by { |date, _ratings| date }.reverse }

  validates :score, presence: true,
                    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 15 }
  validates :movie_id, presence: true
  validates :user_id, presence: true
  validates :watched_date, presence: true

  validate :watched_date_cannot_be_in_the_future

  def watched_date_cannot_be_in_the_future
    return unless watched_date.present? && watched_date > Date.today

    errors.add(:watched_date, "can't be in the future")
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :ratings

  validates :first_name, presence: true, length: { minimum: 1, maximum: 100 }
  validates :last_name, presence: true, length: { minimum: 1, maximum: 100 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
end

app/controllers/ratings_controller.rb
# frozen_string_literal: true

class RatingsController < ApplicationController
  def index
    seed_rating_page
  end

  def create
    @rating = Rating.new(rating_params)

    create_movie if params[:rating][:movie_attributes].present?

    if @rating.save
      flash[:success] = 'Rating was successfully saved'
      redirect_to ratings_path
    else
      flash.now[:error] = 'There was an error recording your rating. Try again!'
      seed_rating_page
      render :index, status: :unprocessable_entity
    end
  end

  def new_movie
    generate_form_rating
    @rating.build_movie
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def select_movie
    generate_form_rating
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  private

  def seed_rating_page
    @ratings = Rating.grouped_and_sorted_by_date || []
    @rebecca = User.find_by(first_name: 'Rebecca')
    @matt = User.find_by(first_name: 'Matt')
    generate_form_rating
  end

  def generate_form_rating
    date = Date.today.strftime('%Y/%m/%d')
    @rating = Rating.new(watched_date: date)
  end

  def rating_params
    params.require(:rating).permit(:score, :user_id, :movie_id, :watched_date, movie_attributes: [:title])
  end

  def create_movie
    movie = @rating.build_movie(rating_params[:movie_attributes])
    movie.save if movie.new_record?
    @rating['movie_id'] = @rating.movie.id
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  include RatingsHelper

  def stats; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/movies_helper.rb
# frozen_string_literal: true

module MoviesHelper
end

app/helpers/ratings_helper.rb
# frozen_string_literal: true

module RatingsHelper
  SCORE_TO_LETTER_GRADE = {
    15 => 'A+',
    14 => 'A',
    13 => 'A-',
    12 => 'B+',
    11 => 'B',
    10 => 'B-',
    9 => 'C+',
    8 => 'C',
    7 => 'C-',
    6 => 'D+',
    5 => 'D',
    4 => 'D-',
    3 => 'F+',
    2 => 'F',
    1 => 'F-',
    -2000 => 'Fart Minus'
  }.freeze

  def matt
    @matt ||= User.find_by(first_name: 'Matt')
  end

  def rebecca
    @rebecca ||= User.find_by(first_name: 'Rebecca')
  end

  def render_rating(rating)
    return "Hasn't seen" if rating.nil?

    score = rating.score
    score = score.round
    SCORE_TO_LETTER_GRADE[score]
  end

  def group_ratings_by_movie(ratings, user1, user2)
    groups = ratings.group_by(&:movie_id).values
    groups.map do |group|
      { title: group[0].movie.title, user1_rating: group.select do |item|
                                                     item[:user_id] == user1.id
                                                   end.first, user2_rating: group.select do |item|
                                                                              item[:user_id] == user2.id
                                                                            end.first }
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!-- prettier-ignore -->
  <head>
    <title>SBSHousehold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> <%= javascript_importmap_tags%>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div>
  <h1>Mecca Movie Log</h1>
  <div class="movies-container">
    <% current_year = nil %> <% current_month = nil %> <% @movies.each do
    |movie| %> <% if current_year != movie.ratings[0].watched_date.year ||
    current_month != movie.ratings[0].watched_date.month %>
    <div class="month-year">
      <h2>
        <%= "#{Date::MONTHNAMES[movie.ratings[0].watched_date.month]}
        #{movie.ratings[0].watched_date.year}" %>
      </h2>
    </div>
    <% current_year = movie.ratings[0].watched_date.year %> <% current_month =
    movie.ratings[0].watched_date.month %> <% end %>
    <div class="movie-row">
      <div class="info-column">
        <div id="title"><%= movie.title %></div>
        <div id="watched-date">
          <%= movie.ratings[0].watched_date.strftime('%d %b') %>
        </div>
      </div>
      <div class="scores-column">
        <div class="rating-column">
          <div class="name-row">Reba</div>
          <div class="rating-row">
            <%= convert_to_letter_grade(movie.ratings[0]) %>
          </div>
        </div>
        <div class="rating-column">
          <div class="name-row">Matt</div>
          <div class="rating-row">
            <%= convert_to_letter_grade(movie.ratings[1]) %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/ratings/_add_new_movie_button.turbo_stream.erb
<div id="movie-button" data-turbo-frame="movie-button">
<%= button_to 'Add New Movie', new_movie_path, method: :post, data: {
turbo_action: 'replace', turbo_frame: 'movie-button movie-form', turbo_method: 'post' } %>
</div>

app/views/ratings/_new_movie_input.html.erb
<div>
  <%= f.fields_for :movie do |movie_fields| %> <%= movie_fields.label :title %>
  <%= movie_fields.text_field :title %> <% end %>
</div>

app/views/ratings/_rate_existing_movie_button.turbo_stream.erb
<div id="movie-button" data-turbo-frame="movie-button">
<%= button_to 'Select existing movie', select_movie_path, method: :post, data: {
turbo_action: 'replace', turbo_frame: 'movie-button movie-form', turbo_method: 'post' } %>
</div>

app/views/ratings/_ratings_form.html.erb
<div id="movie-button" data-turbo-frame="movie-button">
  <%= button_to 'Add New Movie', new_movie_path, method: :post, data: {
  turbo_action: 'replace', turbo_method: 'post', turbo_frame: 'movie-button
  movie-form' } %>
</div>

<%= render partial: 'ratings/forms/initial_form' %>

app/views/ratings/_ratings_row.html.erb
<div>
  <ul>
    <% movie_groups = group_ratings_by_movie(ratings, @rebecca, @matt) %> <%
    movie_groups.each do | group | %>
    <h3><%= group[:title] %></h3>
    <li>
      <%= "Rebecca: #{render_rating(group[:user1_rating])}" %> <%= "Matt:
      #{render_rating(group[:user2_rating])}" %>
    </li>
    <% end %>
  </ul>
</div>

app/views/ratings/forms/_existing_movie_form.html.erb
<%= form_for(@rating) do |f| %>
<div class="field">
  <div id="movie-selection">
    <%= f.label :movie %><br />

    <div>
      <%= f.collection_select(:movie_id, Movie.all.order(:title), :id, :title)
      %>
    </div>
  </div>
</div>

<div class="field">
  <%= f.label :score %><br />
  <%= f.select :score, options_for_select([ ['A+', 15], ['A', 14], ['A-', 13],
  ['B+', 12], ['B', 11], ['B-', 10], ['C+', 9], ['C', 8], ['C-', 7], ['D+', 6],
  ['D', 5], ['D-', 4], ['F', 3], ['F', 2], ['F', 1] ]) %>
</div>

<div class="field">
  <%= f.label :user_id %><br />
  <%= f.collection_select(:user_id, User.all, :id, :first_name) %>
</div>

<div class="field">
  <%= f.label :watched_date %><br />
  <%= f.date_select :watched_date %>
</div>

<div class="actions"><%= f.submit %></div>
<% end %>

app/views/ratings/forms/_existing_movie_form.turbo_stream.erb
<div id="movie-form" data-turbo-frame="movie-form">
<%= form_for(@rating) do |f| %>
<div class="field">
  <div id="movie-selection">
    <%= f.label :movie %><br />

    <div>
      <%= f.collection_select(:movie_id, Movie.all.order(:title), :id, :title)
      %>
    </div>
  </div>
</div>

<div class="field">
  <%= f.label :score %><br />
  <%= f.select :score, options_for_select([ ['A+', 15], ['A', 14], ['A-', 13],
  ['B+', 12], ['B', 11], ['B-', 10], ['C+', 9], ['C', 8], ['C-', 7], ['D+', 6],
  ['D', 5], ['D-', 4], ['F', 3], ['F', 2], ['F', 1] ]) %>
</div>

<div class="field">
  <%= f.label :user_id %><br />
  <%= f.collection_select(:user_id, User.all, :id, :first_name) %>
</div>

<div class="field">
  <%= f.label :watched_date %><br />
  <%= f.date_select :watched_date %>
</div>

<div class="actions"><%= f.submit %></div>
<% end %>
</div>

app/views/ratings/forms/_initial_form.html.erb
<div id="movie-form" data-turbo-frame="movie-form">
  <%= form_for(@rating) do |f| %>
  <div class="field">
    <div id="movie-selection">
      <%= f.label :movie %><br />

      <div>
        <%= f.collection_select(:movie_id, Movie.all.order(:title), :id, :title)
        %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.select :score, options_for_select([ ['A+', 15], ['A', 14], ['A-', 13],
    ['B+', 12], ['B', 11], ['B-', 10], ['C+', 9], ['C', 8], ['C-', 7], ['D+',
    6], ['D', 5], ['D-', 4], ['F', 3], ['F', 2], ['F', 1] ]) %>
  </div>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :first_name) %>
  </div>

  <div class="field">
    <%= f.label :watched_date %><br />
    <%= f.date_select :watched_date %>
  </div>

  <div class="actions"><%= f.submit %></div>
  <% end %>
</div>

app/views/ratings/forms/_new_movie_form.turbo_stream.erb
<div id="movie-form" data-turbo-frame="movie-form">
  <%= form_for(@rating) do |f| %>
  <div class="field">
    <div id="movie-selection">
      <%= f.label :movie %><br />

      <div>
    <%= f.fields_for :movie do |movie_fields| %> <%= movie_fields.label :title %>
    <%= movie_fields.text_field :title %> <% end %>
  </div>
    </div>
  </div>

  <div class="field">
    <%= f.label :score %><br />
    <%= f.select :score, options_for_select([ ['A+', 15], ['A', 14], ['A-', 13],
    ['B+', 12], ['B', 11], ['B-', 10], ['C+', 9], ['C', 8], ['C-', 7], ['D+', 6],
    ['D', 5], ['D-', 4], ['F', 3], ['F', 2], ['F', 1] ]) %>
  </div>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select(:user_id, User.all, :id, :first_name) %>
  </div>

  <div class="field">
    <%= f.label :watched_date %><br />
    <%= f.date_select :watched_date %>
  </div>

  <div class="actions"><%= f.submit %></div>
  <% end %>
</div>

app/views/ratings/index.html.erb
<%= render 'ratings_form' %> <% current_year = nil %> <% current_month = nil %>
<% @ratings.each do |date, ratings| %> <% if date.year != current_year %>
<h2><%= date.year %></h2>
<% current_year = date.year %> <% current_month = nil %> <% end %> <% if
date.month != current_month %>
<h3><%= date.strftime("%B") %></h3>
<% current_month = date.month %> <% end %> <%= render partial: 'ratings_row',
locals: { date: date, ratings: ratings } %> <% end %>

app/views/ratings/new_movie.turbo_stream.erb
<turbo-stream action="replace" target="movie-button">
  <template>
    <%= render 'rate_existing_movie_button' %>
  </template> 
</turbo-stream>

<turbo-stream action="replace" target="movie-form">
  <template>
    <%= render partial: 'ratings/forms/new_movie_form' %>  
  </template>
</turbo-stream>

app/views/ratings/select_movie.turbo_stream.erb
<turbo-stream action="replace" target="movie-button">
  <template>
   <%= render 'add_new_movie_button' %>
  </template>
</turbo-stream>

<turbo-stream action="replace" target="movie-form">
  <template>
    <%= render partial: 'ratings/forms/existing_movie_form'%> 
  </template>
</turbo-stream>

app/views/static_pages/stats.html.erb
<div>
  <h1>Stats</h1>
</div>